package com.SeleniumLib.jase ;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import com.google.common.reflect.Parameter;

import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;
import org.junit.runners.Parameterized.Parameters;

@RunWith(Parameterized.class)
public class CheckQueryTest {
	private String username ;
	private String password ;
	private WebDriver driver;
  private Map<String, Object> vars;
  private Map<String, String> data ;
  JavascriptExecutor js;
  
  public CheckQueryTest(String username, String password) {
	  this.username = username ;
	  this.password = password ;
  }
  
  @Before
  public void setUp() {
	  String firefoxdriver = "F:\\大三\\大三下\\软件测试\\Lab\\Lab2\\GeckoDriver\\geckodriver.exe" ;
	  System.setProperty("webdriver.gecko.driver", firefoxdriver) ;
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  
  @Parameters
  public static Collection<Object[]> getData(){
	  return Arrays.asList(new Object[][] {
		  {"3017218053", "https://gitee.com/chenkuochih/software_test.git"}, 
		  {"3017218054", "https://gitee.com/roshan0/software_test.git"},
		  {"3017218055", "https://gitee.com/dai88X/software_test.git"},
		  {"3017218056", "https://github.com/Bing-Max/SoftwareTest.git"},
		  {"3017218057", "https://github.com/YumengGuo/SoftwareTesting"},
		  {"3017218058", "https://github.com/howAreYouHkk/SoftwareTestingTechnology"},
		  {"3017218059", "https://github.com/Eternal144/Software-Testing"},
		  {"3017218060", "https://gitee.com/HangxueLiu/softwareTest.git"},
		  {"3017218061", "https://github.com/qq734628996/software-test"},
		  {"3017218062", "https://github.com/cxdzb/software-testing-technology"},
		  {"3017218063", "https://github.com/PathfinderTJU/Softwate_test_homework"},
		  {"3017218064", "https://github.com/Martin12345677/software_testing_technology"},
		  {"3017218065", "https://gitee.com/panliming0418/softwareTestingTechnology.git"},
		  {"3017218066", "https://gitee.com/taytaytaytaylor11/SoftwareTesting"},
		  {"3017218067", "https://gitee.com/surumeng/test3017218067"},
		  {"3017218068", "https://gitee.com/Sunhanyu/SoftwareTestingTechnology.git"},
		  {"3017218069", "https://github.com/HaomingSun-1895/Software-Testing-hw.git"},
		  {"3017218070", "https://github.com/Taoboan1999/Taoboan1999"},
		  {"3017218071", "https://github.com/tianzhaotju/software_testing"},
		  {"3017218072", "https://github.com/ZhaomengWang/software_testing"},
	  });
  }
  
  
  @After
  public void tearDown() {
//    driver.quit();
	  driver.close(); 
  }
  @Test
  public void checkQuery() {
    // Test name: CheckQuery
    // Step # | name | target | value
    // 1 | open | /selenium-demo/git-repo | 
    driver.get("http://103.120.226.190/selenium-demo/git-repo");
    // 2 | setWindowSize | 1550x838 | 
    driver.manage().window().setSize(new Dimension(1550, 838));
    // 3 | click | name=user_number | 
    driver.findElement(By.name("user_number")).click();
    // 4 | type | name=user_number | 3017218053
    driver.findElement(By.name("user_number")).sendKeys(this.username);
    // 5 | type | name=password | https://gitee.com/chenkuochih/software_test.git
    driver.findElement(By.name("password")).sendKeys(this.password);
    // 6 | click | css=.btn | 
    driver.findElement(By.cssSelector(".btn")).click();
    // 7 | verifyText | css=.mb-2:nth-child(6) > code | https://gitee.com/chenkuochih/software_test.git
//    /html/body/div/div/div/div/div/div/div[2]/div/form/div[5]/code
//    assertThat(driver.findElement(By.cssSelector(".mb-2:nth-child(6) > code")).getText(), is("https://gitee.com/chenkuochih/software_test.git"));
    String text = driver.findElement(By.xpath("/html/body/div/div/div/div/div/div/div[2]/div/form/div[5]/code")).getText() ;
    System.out.println(this.password);
    System.out.println(text);
    System.out.println((this.password.equals(text)));
  }

}
